### ISSUE TITLE
Support multiple storage classes in the same cluster

### ISSUE THREAD

**Issue by Levovar** [nokia/dynamic-local-pv-provisioner#5]
DLPP :) currently assumes it is the only storage provider in the cluster, there whenever a PVC is created it will be triggered.
Practically however it is possible to provide both local, and remote SAN storage services in the same cluster via StorageClasses API.
DLPP should be enhanced to only handle PVC with local storage class.

**Comment by balintTobik** [comment]
corrected in PR #7
